// Empty array to push buttons that are generated by the searchbox
// for the specific currencies that the user wants to track.

var cryptocurrencies = [];

// Function to render cryptocurrency buttons for personalized menu

function renderButtons() {

	$("#currency-buttons").empty();

	for (var i = 0; i < cryptocurrencies.length; i++) {

		var addButton = $("<button>");
		addButton.addClass("cryptocurrency btn button");
		addButton.attr("data-name", cryptocurrencies[i]);
		addButton.text(cryptocurrencies[i]);
		$("#currency-buttons").append(addButton);
	}
}

var getCurrency = 0;


// Foreign currency converter API that pulls up-to-date information
// on exchange rates between USD and other foreign currencies.


function converterAJAXCall (){

	var converterQueryURL = "http://api.fixer.io/latest?base=USD";

	var getCurrency = $("#currency-dropdown").val();
	var currencySelector = $("<div id='currency-selector'>")
	var currencyLabel = $("<label for='currency-dropdown'>")
	var currencyDropdown = $("<select id='currency-dropdown'>");

	$.ajax({
		url: converterQueryURL,
		method: "GET"
	})
	.done(function(response) {

		console.log(response);

			// Creating foreign currency dropdown with API info

			$.each(response.rates, function (i, val) {
				
				var currencyDropdownOptions = $("<option>");
				currencyDropdownOptions.addClass("currency-dropdown-option");
				currencyDropdownOptions.attr("value", val);
				currencyDropdownOptions.attr("data-name", i);
				currencyDropdownOptions.text(i);
				currencyDropdown.append(currencyDropdownOptions);


				currencySelector.append(currencyLabel);
				currencySelector.append(currencyDropdown);

				$("#header").append(currencySelector);
			});
		})
}

// Calling the converter function
converterAJAXCall ();

// CoinMarketCap API AJAX call function to generate the ticker sidebar

function tickerAJAXCall (){

	var topNumber = "10"
	var TickerQueryURL = "https://api.coinmarketcap.com/v1/ticker/?convert=" + "&limit=" + topNumber;

	// $(".whole-ticker").empty();

	$.ajax({
		url: TickerQueryURL,
		method: "GET"
	})
	.done(function(response) {

		console.log(response);

		$(".whole-ticker").empty();

		var results = response;
		console.log('THIS IS RESPONSE BEFORE LOOP:', results);

		var rowDiv = $("<div class='row'>");
		var columnDiv = $("<div class='four columns whole-ticker'>");
		var eightColumnsDiv = $("<div class='eight columns portfolio'>");
		var currencyDescription = $("<div id='currency-description'>")
		var currencyButtons = $("<div id='currency-buttons'>");


			// This for loop takes the info from the API call
			// and pushes it to the DOM


			for (var i = 0; i < results.length; i++) {

				var tickerDiv = $("<div class='ticker'>");
				var ranking = "<p>" + results[i].rank + ". </p>";
				var currencyName = "<p>" + results[i].name + "  (" + results[i].symbol + ")---$" + results[i].price_usd + "  USD  </p>";
				// var priceUSD = "<p> $" + results[i].price_usd + "  USD  </p>";
				var priceOther = "<p>" + results[i].price_eur + "  Other  </p>";
				var changeOnehour = $("<p>");
				var changeDay = "<p>" + results[i].percent_change_24h + "%  in last 24 hours</p>";

				if (results[i].percent_change_1h > 0) {
					changeOnehour.attr("style", "color: green;");
				}
				else {
					changeOnehour.attr("style", "color: red;");
				}

				tickerDiv.append(ranking);
				tickerDiv.append(currencyName);
				// tickerDiv.append(priceUSD);
				tickerDiv.append((getCurrency * results[i].price_usd).toFixed(2));
				changeOnehour.html(results[i].percent_change_1h + "% in last hour");
				tickerDiv.append(changeOnehour);
				tickerDiv.append(changeDay);
				columnDiv.append(tickerDiv);
				eightColumnsDiv.append(currencyButtons);
				eightColumnsDiv.append(currencyDescription);
				rowDiv.append(eightColumnsDiv);
				rowDiv.append(columnDiv);

				$("#footer").append(rowDiv);
			}

			$( document ).ajaxComplete(function() {
  				console.log( "Triggered ajaxComplete handler." );
				});

			// This listener changes the ticker when the 
			// foreign currency dropdown is changed

			$("#currency-dropdown").on("change", function(){
				getCurrency = $("#currency-dropdown").val();
				$(".whole-ticker").empty();
				tickerAJAXCall();
			});

			// $("#currency-dropdown").on("change", function(){
			// 	// $(".whole-ticker").remove();

			// 	tickerAJAXCall();
			// 	getCurrency = $("#currency-dropdown").val();
			// });
		});
}

// Call function to generate ticker when page loads

tickerAJAXCall();

// Currency search box listener that also calls the renderButtons
// function, which makes a button based on the search and also
// writes that info to the DOM

$("#add-currency").on("click", function(event) {
	event.preventDefault();
	var cryptocurrencyType = $("#currency-input").val().trim();
	cryptocurrencies.push(cryptocurrencyType);
	renderButtons();
	$("#currency-input").val("");
	searchCurrencyAJAXCall (cryptocurrencyType);
});

// CoinMarketCap API AJAX call that pulls the information for
// a specific currency. This is different from the ticker AJAX
// call because the ticker only pulls a set amount of info (limit)
// but this call will search all 1100+ currencies on CoinMarketCap.

function searchCurrencyAJAXCall (currency){

	var searchQueryURL = "https://api.coinmarketcap.com/v1/ticker/" + currency + "/";

	$.ajax({
		url: searchQueryURL,
		method: "GET"
	})
	.done(function(response) {

		console.log(response);
		var results = response;
		var searchedCurrencyDiv = $("<div class='searched'>");
		var USDConverterForm = $("<form id='usd-to-crypto'>");
		var USDConverterFormLabel = $("<label for='usd-to-crypto-box'>");
		var USDConverterFormInput = $("<input type='text' id='usd-to-crypto-box'>");
		var converterResults = $("<div id='converter-results'>");

		searchedCurrencyDiv.attr("style", "color: blue;");

		searchedCurrencyDiv.append("<p>" + results[0].rank + ". </p>");
		searchedCurrencyDiv.append("<p> $" + results[0].price_usd + " USD</p>");
		searchedCurrencyDiv.append("<p>" + results[0].percent_change_1h + "% in last hour</p>");
		searchedCurrencyDiv.append("<p>" + results[0].percent_change_24h + "% in last 24 hours</p>");
		searchedCurrencyDiv.append(USDConverterForm);
		USDConverterFormLabel.text("Convert  " + results[0].name + " to USD");
		USDConverterForm.append(USDConverterFormLabel);
		USDConverterFormInput.attr("placeholder", "Convert " + results[0].name + "to USD");
		USDConverterForm.append(USDConverterFormInput);
		searchedCurrencyDiv.append(converterResults);


		$("#currency-description").append(searchedCurrencyDiv);

				// Change function that listens for a change in the
				// converter box to change from cryptocurrency to USD

				$("#usd-to-crypto-box").on("change", function(){
					var userUSD = $("#usd-to-crypto-box").val();
					var userMoneyConverter = (results[0].price_usd * userUSD);
					$("#converter-results").text("$" + userMoneyConverter.toFixed(2) + " USD");

				});

			});
}







